### ISSUE TITLE
Problem when downloading datasets from our servers

### ISSUE THREAD

**Issue by anaschwendler** [okfn-brasil/serenata-toolbox#186]
This template is here to help you to write your issue ;)

**What is the problem?**
Apparently, when you download the datasets from our servers, it still returns an error:

![image](https://user-images.githubusercontent.com/4131432/37486363-041d339a-286d-11e8-8a43-e45b7e7efdca.png)

**How can this be addressed?**
I seem that only by changing `serenata-toolbox/datasets/remote.py` line 57 for:
```
bucket=self.remote.BUCKET,
```
may work, but I recommend making a regression test for it.

**Who could help with this issue?**
@cuducos may be the best because he was already working on it! 

**Labels**
[bug]

**Comment by cuducos** [comment]
Totally agree with the proposed solution. That's something I should have noticed myself and changed in #184. My bad, I missed it.

**Comment by cuducos** [comment]
I don't think so. There are only 3 occurrences of _bucket_ and if you're unable to reproduce it, I guess it is already fixed ; ) Tks
