### ISSUE TITLE
Is there a data dictionary for the chamber of deputies reimbursements?

### ISSUE THREAD

**Issue by mnunes** [okfn-brasil/serenata-toolbox#188]
**What is the problem?**
I couldn't find a data dictionary for the chamber of deputies reimbursements provided by serenata toolbox. For example, I am not sure about the difference between the columns 'document_value', 'remark_value', 'total_net_value', and 'total_value'. I found this [cached link on Google](https://webcache.googleusercontent.com/search?q=cache:30SVdotP9M0J:https://github.com/datasciencebr/serenata-de-amor/blob/master/docs/federal-budget-agreements-datasets.md+&cd=1&hl=en&ct=clnk&gl=br), but it didn't solve my problem.

**How can this be addressed?**
Giving a link for the data dictionary or writing one.

**Who could help with this issue?**
Anyone who knows the data columns meaning.

**Comment by cuducos** [comment]
Sure thing! [Here’s the offical page on that](http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/explicacoes-sobre-o-formato-dos-arquivos-xml) in pt-BR. In `research/src/` there’s a script to translate it : )

**Comment by mnunes** [comment]
My bad. Thanks.

**Comment by cuducos** [comment]
Not bad at all, good question! No worries
