### ISSUE TITLE
function test_download_no_file() duplicated

### ISSUE THREAD

**Issue by willianpaixao** [okfn-brasil/serenata-toolbox#195]
Hello,

is there any reason why `test_download_no_file()` in `tests/unit/test_datasets_downloader.py` is duplicated (currently lines 47 and 84)?

I don't know if any change is expected in the second execution or just a copy and paste error. If the first option is true, a comment explaining would be nice.

Kind regards,
Willian Paixao

**Comment by cuducos** [comment]
Probably some clumsy copy & paste. We can safely delete one of them ; ) Good catch
