### ISSUE TITLE
README.rst broken links related to generating datasets

### ISSUE THREAD

**Issue by disouzaleo** [okfn-brasil/serenata-toolbox#202]
It seems that the **README.rst** have some broken links related to the older version of the original Serenata de Amor repo, mainly those related to the generating the datasets section. The **CONTRIBUTING.md** at the /research/ at Serenata seems to not exist anymore.

With some explanation where this info can go, I can fix this.

**Comment by cuducos** [comment]
Hi @Lrodlima, many thanks for this issue.

I just made a bit of Git-archeology and found the (purportedly) last version of the `CONTRIBUTING.md` with the references used in the toolbox's `README.md`. This version is outdated and unmaintained, but I think that for the purpose of the toolbox it does the job and we can link to this URL (adding the `#name-of-the-section` accordingly):

https://github.com/okfn-brasil/serenata-de-amor/blob/51fad8c807cb353303c5f5a3f945693feeb82015/CONTRIBUTING.md

Does it make sense to you, @jtemporal?

**Comment by Lrodlima** [comment]
Cool I will do it. :muscle:

**Comment by vbernardes** [comment]
I was reading through **README.rst** and it seems the broken links are still there... I can take the URL provided by @cuducos and update the links, if that's all right.

**Comment by cuducos** [comment]
Closed by #215
