### ISSUE TITLE
Add geolocation to the latest companies dataset

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/serenata-toolbox#57]
The latest `companies` dataset (actually `2017-04-27-companies-no-geolocation.xz`) has no geolocation info. The `src/geocode_addresses.py` script can handle that ; )

**Comment by cuducos** [comment]
And the new one too (`2017-05-21`)

**Comment by starknx** [comment]
How is generated this dataset? I looking for something like this to a geomarketing software..

**Comment by cuducos** [comment]
Hi @starknx – my fault, sorry… the script mentioned is in [the main repo](http://github.com/datasciencebr/serenata-de-amor).

**Comment by cuducos** [comment]
Closed in favor of #218
